name: Upload JSON to GitHub

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Upload JSON file
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        echo '${{ secrets.GH_TOKEN }}' > token.txt
        curl -X PUT \
        -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
        -H "Content-Type: application/json" \
        -d '{
          "message": "Upload JSON",
          "content": "'$(cat data.json | base64)'"
        }' \
        https://api.github.com/repos/${{ github.repository }}/contents/data/upload.json
